name: CI

on:
  push:
    branches: [ main, feature/ci-cd ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      ## this code listens to requests forever
      # - name: Check app starts
      #   run: |
      #     python app.py

      ## the app.py is imported (if there is an error, it won't be imported)
      - name: Check code imports
        run: python -c "import app"
